"""empty message

Revision ID: 38a24177376a
Revises: 
Create Date: 2019-08-19 04:29:43.123745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a24177376a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer', sa.Column('trainer_contact', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer', 'trainer_contact')
    # ### end Alembic commands ###
