"""empty message

Revision ID: 42dfbbdee8e5
Revises: fe7a199a45d3
Create Date: 2019-07-01 15:58:11.190548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dfbbdee8e5'
down_revision = 'fe7a199a45d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('pool_tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'pool_tag')
    # ### end Alembic commands ###
