"""empty message

Revision ID: 693c0d5d90f6
Revises: a84934732cd0
Create Date: 2019-06-30 02:13:48.820991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693c0d5d90f6'
down_revision = 'a84934732cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('sanya', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'sanya')
    # ### end Alembic commands ###
