"""empty message

Revision ID: a84934732cd0
Revises: 2aabf4f0db3a
Create Date: 2019-06-30 02:08:38.208540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84934732cd0'
down_revision = '2aabf4f0db3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'pool_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('pool_tag', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
