"""empty message

Revision ID: b04b94c6830c
Revises: 42dfbbdee8e5
Create Date: 2019-07-02 01:29:34.338229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04b94c6830c'
down_revision = '42dfbbdee8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'pool_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('pool_tag', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
