"""empty message

Revision ID: b5880a350d4c
Revises: b04b94c6830c
Create Date: 2019-07-02 01:30:31.722672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5880a350d4c'
down_revision = 'b04b94c6830c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('pool_tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'pool_tag')
    # ### end Alembic commands ###
