"""empty message

Revision ID: b65a9b2f1293
Revises: b5880a350d4c
Create Date: 2019-07-02 01:40:36.346078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65a9b2f1293'
down_revision = 'b5880a350d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('tag', sa.Text(), nullable=True))
    op.drop_column('pool', 'pool_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('pool_tag', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pool', 'tag')
    # ### end Alembic commands ###
