"""empty message

Revision ID: e235870556b5
Revises: b65a9b2f1293
Create Date: 2019-07-02 01:56:58.694169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e235870556b5'
down_revision = 'b65a9b2f1293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
