"""empty message

Revision ID: fe7a199a45d3
Revises: 693c0d5d90f6
Create Date: 2019-06-30 02:16:35.608054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7a199a45d3'
down_revision = '693c0d5d90f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'sanya')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('sanya', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
